# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input().strip())
STDIN = ''

def strng(STDIN):
    s1=[]
    s2=[]
    for i in range(len(STDIN)):
        if i%2==0:
            s1.append(STDIN[i])
        else:
            s2.append(STDIN[i])
    out = "".join(s1) + " " + "".join(s2)
    print(out)

for i in range(n):
    STDIN = input()
    strng(STDIN)

